version: '3.8'
services:
  web:
    build:
      context: web
    ports: 
      - "5001:80"
    volumes:
      - ./web:/usr/src/app/
      - /usr/src/app/node_modules
    networks:
      - frontend

  app:
    build:
      context: app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./app:/usr/src/app/
      - /usr/src/app/node_modules
    networks:
      - frontend
      - backend

  postgres:
    image: postgres:14.1-alpine
    restart: always
    ports:
      # Standard port for PostgreSQL databases
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    volumes:
      - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
    networks:
      - backend


  # backup:
  #   # TODO configure
  #   image: eeshugerman/postgres-backup-s3:15
  #   environment:
  #     SCHEDULE: '@weekly'     # optional
  #     BACKUP_KEEP_DAYS: 7     # optional
  #     PASSPHRASE: passphrase  # optional
  #     S3_REGION: region
  #     S3_ACCESS_KEY_ID: key
  #     S3_SECRET_ACCESS_KEY: secret
  #     S3_BUCKET: my-bucket
  #     S3_PREFIX: backup
  #     POSTGRES_HOST: postgres
  #     POSTGRES_DATABASE: dbname
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password


networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
