version: '3.8'
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    networks:
      - postgres

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
    networks:
      - postgres

  # backup:
  #   # TODO configure
  #   image: eeshugerman/postgres-backup-s3:15
  #   environment:
  #     SCHEDULE: '@weekly'     # optional
  #     BACKUP_KEEP_DAYS: 7     # optional
  #     PASSPHRASE: passphrase  # optional
  #     S3_REGION: region
  #     S3_ACCESS_KEY_ID: key
  #     S3_SECRET_ACCESS_KEY: secret
  #     S3_BUCKET: my-bucket
  #     S3_PREFIX: backup
  #     POSTGRES_HOST: postgres
  #     POSTGRES_DATABASE: dbname
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password


networks:
  postgres:
    driver: bridge
